name: Java Build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
        # This should match https://github.com/highbyteinc/intelligencehub/blob/main/Dockerfile#L24
          java-version: '11'
          distribution: 'temurin'
          server-id: github
      
      - name: Show Settings.xml
        run: cat $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn --batch-mode clean install
      
      - name: Publish to GitHub Packages
        run: |
          mvn \
            -s $HOME/.m2/settings.xml \
            --batch-mode \
            deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}